name: 02 - Workflow Event

on: push 
jobs:
  echo:  
    runs-on: ubuntu-latest
    steps:
      - name: show the triger
        run: echo " I have triggerd by a(n) ${{ github.event_name}} event"
        