name: 04- Using actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkingout the code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - name: install dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app
      

  # 0 checking out the code from the repository
  # 1 Going to install the dependencies of the React application
  # 2 Execute automated tests 